// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-xfd90P3ogcbmKbLMOMDZAugi5JM9ckQ',
    appId: '1:870005085361:web:ed9e1eeca3e116fc08fe90',
    messagingSenderId: '870005085361',
    projectId: 'smiley-food-84b46',
    authDomain: 'smiley-food-84b46.firebaseapp.com',
    storageBucket: 'smiley-food-84b46.firebasestorage.app',
    measurementId: 'G-0PMXYBRPLF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJPiniJaVea04v01DAixBrGd0Fiqh-8-o',
    appId: '1:870005085361:ios:3a4b889528c9ff8a08fe90',
    messagingSenderId: '870005085361',
    projectId: 'smiley-food-84b46',
    storageBucket: 'smiley-food-84b46.firebasestorage.app',
    iosBundleId: 'com.example.smileyFoods',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJPiniJaVea04v01DAixBrGd0Fiqh-8-o',
    appId: '1:870005085361:ios:3a4b889528c9ff8a08fe90',
    messagingSenderId: '870005085361',
    projectId: 'smiley-food-84b46',
    storageBucket: 'smiley-food-84b46.firebasestorage.app',
    iosBundleId: 'com.example.smileyFoods',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-xfd90P3ogcbmKbLMOMDZAugi5JM9ckQ',
    appId: '1:870005085361:web:3848e13758986d3708fe90',
    messagingSenderId: '870005085361',
    projectId: 'smiley-food-84b46',
    authDomain: 'smiley-food-84b46.firebaseapp.com',
    storageBucket: 'smiley-food-84b46.firebasestorage.app',
    measurementId: 'G-H1PDCJLFD9',
  );

}